# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release Jmeter gRPC Plugin

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up dependencies
        run: |
          mvn clean install -Dmaven.test.skip=true
      - name: Check cacert
        run: |
          ls -la
          printf "changeit" |  keytool -list -v -keystore dist/cert/cacertslocal
        if: always()
      - name: Run unit test
        run: |
          export DISPLAY=localhost:0
          mvn test -Djavax.net.ssl.trustStore=dist/cert/cacertslocal -Djavax.net.ssl.trustStorePassword=changeit
        if: always()
      - name: Verify Dummy Log
        run: |
          cat grpc-dummy-server.log
        if: always()