# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release Jmeter gRPC Plugin

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up dependencies
        run: |
          mvn clean install -Dmaven.test.skip=true
      - name: Run unit test
        run: |
          mvn test
          cat grpc-dummy-server.log
      - name: Verify Dummy Log
        run: |
          cat grpc-dummy-server.log